### ISSUE TITLE
detect hard linked clones

### ISSUE THREAD

**Issue by wkretzsch** [rtyley/bfg-repo-cleaner#118]
Hi,
I just performed the following commands
````
git clone --mirror myRepo myRepo.git
java -jar ~/opt/bfg-1.12.7.jar --strip-blobs-bigger-than 50M myRepo.git
````
and got 

````
Cleaning
--------

Found 6285 commits
Cleaning commits:        99% (6223/6285)Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.jgit.errors.MissingObjectException: Missing commit 74da5d4e6355c4d4dce30cdb8dbf7ee6fe799c6e
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)

etc...
````

Cloning explicitly using 
````
git clone --mirror file:///path/to/myRepo myRepo.git
````
solves the problem.

It might be good to keep people from doing a hard link based clone like I did.

**Comment by MsRaelyn298** [comment]
Hey how do I get rid of jt

**Comment by MsRaelyn298** [comment]
It

**Comment by wkretzsch** [comment]
Are you saying this was once a feature of bfg?

**Comment by MsRaelyn298** [comment]
Yep and I am just gaining control of a serious issue of my privacy being invaded

**Comment by MsRaelyn298** [comment]
I could use all the help

**Comment by MsRaelyn298** [comment]
Your from the UK? I think I just about got n figured out OMG I was up all
freaking night I'm still working on it
