### ISSUE TITLE
Getting stackoverflow error, and a very weird error stack

### ISSUE THREAD

**Issue by kumarharsh** [rtyley/bfg-repo-cleaner#174]
I'm trying to replace a particular text in my repo (in any file) with another text.
I've defined this replacement:
```
/abc.com/old-repo==>/abc.com/new-repo
```

When I run this command:
```
java -jar C:\bin\misc\bfg-1.12.13.jar -rt replace.txt
```

It outputs:
```
Using repo : C:\Workspace\abc.com\new-project\.git                
                                                                                           
Found 1704 objects to protect                                                              
Found 11 commit-pointing refs : HEAD, refs/heads/develop, ...   
                                                                                           
Protected commits                                                                          
-----------------                                                                          
                                                                                           
These are your protected commits, and so their contents will NOT be altered:               
                                                                                           
 * commit 3bea33d6 (protected by 'HEAD')                                                   
                                                                                           
Cleaning                                                                                   
--------                                                                                   
Found 5221 commits
Cleaning commits:        25% (1306/5221)
```

and then, it crashes with this stack-trace:
```
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError:
... a lot of times! ...
...
... and finally ...
...
util.concurrent.ExecutionError: java.lang.StackOverflowError
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:113)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:112)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply$mcV$sp(RepoRewriter.scala:111)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
        at com.madgag.git.bfg.Timing$.measureTask(timing.scala:40)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:104)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:145)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:59)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
```

Running bfg on Windows 10 machine on Powershell. Java "1.8.0_101"

**Comment by rtyley** [comment]
Are you able to share the repo with me?

**Comment by rnelsonxmission** [comment]
I was getting this error, and was able to resolve it by increasing the Java VM stack size.  You can do this with "java -Xss10m bfg ...".  This is a 10MB stack which is most certainly overkill, but I didn't experiment with smaller stacks to find the smallest that got me through the problem.
