### ISSUE TITLE
help (java.nio.charset.IllegalCharsetNameException: utf-8,ISO-8859-1)

### ISSUE THREAD

**Issue by sunhao123** [rtyley/bfg-repo-cleaner#179]
i use the bfg-repo-cleaner to clean my repo.
use this command : java -Dfile.encoding="UTF-8" -jar bfg.jar --private --strip-blobs-bigger-than 100M  NW_Router_V8_MAIN.git

But every time, I get this error:

`Found 169315 commits
Cleaning commits:        15% ( 25398/169315)Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.IllegalCharsetNameException: utf-8,ISO-8859-1
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:113)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:112)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply$mcV$sp(RepoRewriter.scala:111)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
        at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
        at com.madgag.git.bfg.Timing$.measureTask(timing.scala:40)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:104)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:145)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:59)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.IllegalCharsetNameException: utf-8,ISO-8859-1
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:87)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:85)
        at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 28 more
Caused by: java.nio.charset.IllegalCharsetNameException: utf-8,ISO-8859-1
        at java.nio.charset.Charset.checkName(Charset.java:320)
        at java.nio.charset.Charset.lookup2(Charset.java:496)
        at java.nio.charset.Charset.lookup(Charset.java:475)
        at java.nio.charset.Charset.forName(Charset.java:540)
        at org.eclipse.jgit.util.RawParseUtils.parseEncoding(RawParseUtils.java:791)
        at org.eclipse.jgit.revwalk.RevCommit.getEncoding(RevCommit.java:529)
        at com.madgag.git.bfg.model.CommitNode$.apply(Commit.scala:62)
        at com.madgag.git.bfg.model.Commit$.apply(Commit.scala:33)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:100)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:98)
        at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 39 more`
I've actually ran bfg on another repository which was much bigger too. Also, I've just updated Java with no luck.
@rtyley

**Comment by javabrett** [comment]
It looks like you have one or more commits somewhere in your history which have a corrupt encoding specified (`utf-8,ISO-8859-1` looks like a list).  This is not unheard-of.

To confirm, you can create a report like this:

    git log --all --pretty=raw | grep "^encoding" | sort | uniq -c

That should tell you how many commits you are dealing with.  Depending on the number you could then inspect a couple or identify them all.

BFG currently has no provision for dealing with this corruption, as you see above.  You could rewrite a larger set of impacted commits using `git filter-branch`, then run BFG after that.
