### ISSUE TITLE
Exception in thread "main" org.eclipse.jgit.errors.LargeObjectException

### ISSUE THREAD

**Issue by Vuader** [rtyley/bfg-repo-cleaner#184]
Running bfg to remove some files from my repo:

    java -jar ~/scripts/bfg-1.12.14.jar --delete-files *.zip .

Fails with this error:

    Exception in thread "main" org.eclipse.jgit.errors.LargeObjectException: 8f35a86d53b408094569c3def2132e0fcc15aea5 exceeds size limit
        at org.eclipse.jgit.internal.storage.file.LargePackedWholeObject.getCachedBytes(LargePackedWholeObject.java:98)
        at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:214)
        at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:248)
        at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:226)
        at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:70)
        at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1210)
        at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:828)
        at com.madgag.git.package$RichTreeWalk$$anon$1.next(package.scala:135)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at com.madgag.git.package$RichTreeWalk$$anon$1.foreach(package.scala:128)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at com.madgag.git.package$RichTreeWalk$$anon$1.to(package.scala:128)
        at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:304)
        at com.madgag.git.package$RichTreeWalk$$anon$1.toSet(package.scala:128)
        at com.madgag.git.package$.allBlobsUnder(package.scala:268)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$6.apply(ProtectedObjectCensus.scala:83)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$6.apply(ProtectedObjectCensus.scala:83)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.apply(ProtectedObjectCensus.scala:83)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection$lzycompute(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:57)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)

On UBUNTU server with:

    java -version
    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by pacho2** [comment]
I think the same as issue 225 (that one shows a solution)

**Comment by mattrussell2** [comment]
link: https://github.com/rtyley/bfg-repo-cleaner/issues/225
