### ISSUE TITLE
The delete-folders option hits an assertion

### ISSUE THREAD

**Issue by matej** [rtyley/bfg-repo-cleaner#19]
I just tried the new `--delete-folders` option while trying to salvage a hg -> git migration that is causing problems due to .git references buried deep in the commit history. Unfortunately I keep hitting an exception. 

Any suggestions?

```
$ java -jar /Users/matej/Downloads/bfg-1.6.0.jar --delete-folders .git --no-blob-protection

Using repo : /Users/matej/Documents/Work/app

Found 0 objects to protect
Exception in thread "main" java.lang.AssertionError: assertion failed: Can't find any refs in repo at /Users/matej/Documents/Work/app
    at scala.Predef$.assert(Predef.scala:179)
    at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:67)
    at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:57)
    at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:35)
    at scala.Option.map(Option.scala:145)
    at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:34)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
    at com.madgag.git.bfg.cli.Main.main(Main.scala)
```

**Comment by Gmskjunior** [comment]
$ bfg --delete-folders .git --delete-files .git  --no-blob-protection  my-repo.git
