### ISSUE TITLE
UnsupportedCharsetException: koi8r

### ISSUE THREAD

**Issue by StupidScience** [rtyley/bfg-repo-cleaner#237]
Hello.
Looks like my issue is similar to #179
I receive the following errors:

```
Cleaning commits:         6% ( 12561/200493)Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.UnsupportedCharsetException: koi8r
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:113)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:112)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply$mcV$sp(RepoRewriter.scala:111)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
	at com.madgag.git.bfg.Timing$.measureTask(timing.scala:40)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:104)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:145)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:60)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:35)
	at scala.Option.map(Option.scala:146)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:34)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.UnsupportedCharsetException: koi8r
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:87)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:85)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 28 more
Caused by: java.nio.charset.UnsupportedCharsetException: koi8r
	at java.base/java.nio.charset.Charset.forName(Charset.java:541)
	at org.eclipse.jgit.util.RawParseUtils.parseEncoding(RawParseUtils.java:791)
	at org.eclipse.jgit.revwalk.RevCommit.getEncoding(RevCommit.java:529)
	at com.madgag.git.bfg.model.CommitNode$.liftedTree1$1(Commit.scala:64)
	at com.madgag.git.bfg.model.CommitNode$.apply(Commit.scala:64)
	at com.madgag.git.bfg.model.Commit$.apply(Commit.scala:34)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:100)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:98)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 39 more

```

result of command 
```
git log --all --pretty=raw | grep "^encoding" | sort | uniq -c

   1 encoding cp1251
2716 encoding koi8r
```

**Comment by javabrett** [comment]
Which version of BFG are you using?  The fix for #179 is supposed to be in v1.12.14 and v1.12.15.

**Comment by StupidScience** [comment]
Same issue in 1.12.16

**Comment by javabrett** [comment]
OK I see the difference - in #179 a `IllegalCharsetNameException` is thrown (and now caught), whereas you are seeing a `UnsupportedCharsetException`, which will also need to be caught.  This will require an updated patch.
