### ISSUE TITLE
Error messages related to 'HEAD' pointer.

### ISSUE THREAD

**Issue by dongbum** [rtyley/bfg-repo-cleaner#244]
I have seen these error messages when using the bfg cleaner.
I use git-flow and my repositorie have only 'develop' branch. (Does not have 'HEAD' pointer.)

I would like to work even if there is only have 'develop' branch. (No 'HEAD' pointer.)

```
[root@localhost git-repo]# java -jar bfg-1.12.16.jar --strip-blobs-bigger-than 50M MyGITProject.git

Using repo : /home/git-repo/MyGITProject.git

Scanning packfile for large blobs: 529
Scanning packfile for large blobs completed in 51 ms.
Found 1 blob ids for large blobs - biggest=134283264 smallest=134283264
Total size (unpacked)=134283264
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't find 'HEAD' in /home/git-repo/MyGITProject.git - are you sure that exists?
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$3$$anonfun$apply$1.apply(ProtectedObjectCensus.scala:67)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$3$$anonfun$apply$1.apply(ProtectedObjectCensus.scala:67)
        at scala.Option.getOrElse(Option.scala:121)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$3.apply(ProtectedObjectCensus.scala:67)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$3.apply(ProtectedObjectCensus.scala:66)
        at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:321)
        at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:320)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:320)
        at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.apply(ProtectedObjectCensus.scala:66)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection$lzycompute(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:58)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:35)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:34)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
[root@localhost git-repo]#
```

**Comment by javabrett** [comment]
Some questions:

- How did you obtain `MyGITProject.git` - was it a bare clone of some remote repo?
- Does `git fsck` report anything unusual?
- Do you have a `HEAD` file in your repo pointing to some commit?  Is it a valid commit?

If you want to run without protected branches and hopefully bypass this problem, just use `--no-blob-protection`.
