### ISSUE TITLE
Crash with large trace

### ISSUE THREAD

**Issue by laurin1** [rtyley/bfg-repo-cleaner#291]
I've been removing files and folders from a very large repo (in history) and had no trouble. However, now that I have truncated the history, stripped all tags and all branches except the master, this causes a crash:

**C:\Git\cmd\bfg.bat --delete-folders Intranet c:\inetpub\Elements4**

This is my batch file:

**java -Xss10m -jar %~dp0bfg.jar %1 %2 %3 %4 %5**

I added the -Xss10m per the comment in https://github.com/rtyley/bfg-repo-cleaner/issues/174, as the trace exits before it finishes. Even with 10mb, the trace still exits (looks like it's in a loop).

How do I troubleshoot this issue?

Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        ... 1024 more
Caused by: java.lang.StackOverflowError
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:632)
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:53)
        at com.google.common.cache.LocalCache$LoadingValueReference.setException(LocalCache.java:3516)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3559)
        ... 1008 more

**Comment by laurin1** [comment]
I've verified that this occurs with --delete-files as well.

**Comment by laurin1** [comment]
I found what changed. Now, before I run the BFG, I am removing a remote (the only remote):

**git remote rm origin**

Works fine unless I run this command first.

**Comment by laurin1** [comment]
I found a workaround. Cloning the repo does not fix it. I have to create a new repo and pull from the "bad" one, then it no longer crashes.

**Comment by joshmoore** [comment]
Ran into the same with 1.13.0:
```
	at com.madgag.git.bfg.MemoUtil$$anon$1.apply(memo.scala:61)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.madgag.git.bfg.model.CommitArcs.cleanWith(Commit.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner.$anonfun$cleanCommit$1(ObjectIdCleaner.scala:102)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
```
Same workaround worked for me. :+1:
