### ISSUE TITLE
Why can't it detect a file that's more than 100MB

### ISSUE THREAD

**Issue by abrhambas01** [rtyley/bfg-repo-cleaner#389]
When I try to push a repo

![image](https://user-images.githubusercontent.com/12043306/82275773-2742ac80-99b6-11ea-9040-7649608e9289.png)

but when I use `bfg-repo-cleaner` w/ 

`git clone --mirror https://github.com/abrhambas01/blacktrail-backup`

![image](https://user-images.githubusercontent.com/12043306/82275886-67a22a80-99b6-11ea-9403-e06c47a6e88f.png)

I don't know why it doesn't detect the 120MB .rar file

**Comment by abrhambas01** [comment]
So  from what I understand from this is to clone from the old repo, since I'm trying to push 2 a new repo here in github
```
git clone --mirror  git@github.com:abrhambas01/blacktrail-backup.git
```
```
java -jar bfg.jar --strip-blobs-bigger-than 100M git@github.com:abrhambas01/blacktrail-backup.git
```
But I get,
> Aborting : git@github.com:abrhambas01\blacktrail-backup.git is not a valid Git repository.

**Comment by javabrett** [comment]
```
java -jar bfg.jar --strip-blobs-bigger-than 100M git@github.com:abrhambas01/blacktrail-backup.git
```
See https://rtyley.github.io/bfg-repo-cleaner/#usage .  After mirror cloning, BFG works on local repo `blacktrail-backup.git`.

**Comment by abrhambas01** [comment]
Dude @javabrett, What I'm trying to do bro is to delete this pesky 120+mb .rar backup of the project that I was doing, sorry bro I'm dumb with git and I already set the URL to a new repo since I'll be migrating all the project to there..

**Comment by abrhambas01** [comment]
```
$ git remote get-url origin
git@github.com:abrhambas01/blacktrail-new.git
```
> WHen i do this, I get the private repo that I was trying to push the new project there.

**Comment by abrhambas01** [comment]
Looks like an improvement on my side
```
Using repo : F:\laragon_2\www\blacktrail\..\blacktrail-backup2.git

Scanning packfile for large blobs: 3172
Scanning packfile for large blobs completed in 721 ms.
Found 1 blob ids for large blobs - biggest=134407226 smallest=134407226
Total size (unpacked)=134407226
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at use.newer.java.Util.invokeMainMethod(Util.java:89)
        at use.newer.java.Util.executeMainProgram(Util.java:28)
        at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
        at use.newer.java.Version8.main(Version8.java:5)
Caused by: java.lang.IllegalArgumentException: Couldn't find 'HEAD' in F:\laragon_2\www\blacktrail\..\blacktrail-backup2.git - are you sure that exists?
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.$anonfun$apply$2(ProtectedObjectCensus.scala:68)
        at scala.Option.getOrElse(Option.scala:121)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.$anonfun$apply$1(ProtectedObjectCensus.scala:67)
        at scala.collection.TraversableLike.$anonfun$groupBy$1(TraversableLike.scala:321)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at scala.collection.TraversableLike.groupBy(TraversableLike.scala:320)
        at scala.collection.TraversableLike.groupBy$(TraversableLike.scala:318)
        at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
        at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.apply(ProtectedObjectCensus.scala:66)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection$lzycompute(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.CLIConfig.objectProtection(CLIConfig.scala:145)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1(Main.scala:58)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1$adapted(Main.scala:35)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:35)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
        ... 8 more
```

**Comment by asmwarrior** [comment]
I'm on Windows too. I also see such 

~~~~
Couldn't find 'HEAD'
~~~~

Error.

But after adding the option `--no-blob-protection`, this error is gone. 

Hope this helps, but I'm still not sure why this option solves the issue.
