### ISSUE TITLE
report tries to write outside of home directory

### ISSUE THREAD

**Issue by xenoterracide** [rtyley/bfg-repo-cleaner#440]
```
 bfg --delete-files .pgpass ~/.local/share/yadm/repo.git                                                                                                      # brix

Using repo : /home/xeno/.local/share/yadm/repo.git

Found 51 objects to protect
Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at use.newer.java.Util.invokeMainMethod(Util.java:89)
        at use.newer.java.Util.executeMainProgram(Util.java:28)
        at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
        at use.newer.java.Version8.main(Version8.java:5)
Caused by: java.nio.file.AccessDeniedException: /home/xeno.bfg-report
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
        at java.base/java.nio.file.Files.createDirectories(Files.java:783)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportsDir$lzycompute(Reporter.scala:64)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportsDir(Reporter.scala:52)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportProtectedCommitsAndTheirDirt(Reporter.scala:130)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportObjectProtection(Reporter.scala:106)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:96)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1(Main.scala:59)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1$adapted(Main.scala:34)
        at scala.Option.map(Option.scala:242)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:34)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
        ... 8 more
```

```
 bfg --version                                                                                                                                                  # brix
bfg 1.14.0
```

**Comment by darioseidl** [comment]
I get the same error with version 1.14.0, and the `--delete-files` operation doesn't run.

With version 1.13.0, `--delete-files` runs, but there is still a "No such file or directory" error afterwards. The error probably also comes from writing the `.bfg-report`, afaict from the stack trace, 

```
$ bfg --delete-files 'someFiles'            

Using repo : /home/dario/.git

Found 566 objects to protect
Found 3 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/master

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 91bdf9f8 (protected by 'HEAD')

Cleaning
--------

Found 1366 commits
Cleaning commits:       100% (1366/1366)
Cleaning commits completed in 1,132 ms.

Updating 2 Refs
---------------

	Ref                          Before     After   
	------------------------------------------------
	refs/heads/master          | 91bdf9f8 | 34cb8c92
	refs/remotes/origin/master | 91bdf9f8 | 34cb8c92

Updating references:    100% (2/2)
...Ref update completed in 55 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	.......................DDDDDDDDDDmmmmmmmmmmmmmmmmmmmmmmmmmmm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After   
	-------------------------------------------
	First modified commit | 9ee5ec31 | 48b7074a
	Last dirty commit     | f507a9e7 | 0f8d3055

Deleted files
-------------

	Filename                      Git id             
	-------------------------------------------------
        <someFiles>
	...
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at use.newer.java.Util.invokeMainMethod(Util.java:89)
	at use.newer.java.Util.executeMainProgram(Util.java:28)
	at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
	at use.newer.java.Version8.main(Version8.java:5)
Caused by: java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
	at java.base/java.io.File.createNewFile(File.java:1045)
	at scalax.io.support.FileUtils$.$anonfun$preOpen$1(FileUtils.scala:66)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scalax.io.support.FileUtils$.preOpen(FileUtils.scala:58)
	at scalax.io.support.FileUtils$.$anonfun$openOutputStream$1(FileUtils.scala:19)
	at scalax.io.managed.OutputStreamResource.nResource$1(OutputStreamResource.scala:38)
	at scalax.io.managed.OutputStreamResource.$anonfun$writableByteChannel$1(OutputStreamResource.scala:40)
	at scalax.io.managed.WritableByteChannelResource.nResource$2(WritableByteChannelResource.scala:35)
	at scalax.io.managed.WritableByteChannelResource.$anonfun$writer$1(WritableByteChannelResource.scala:37)
	at scalax.io.managed.WriterResource.open(WriterResource.scala:17)
	at scalax.io.Resource.$anonfun$acquireFor$1(Resource.scala:164)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:248)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at scala.util.control.Exception$Catch.either(Exception.scala:248)
	at scalax.io.Resource.acquireFor(Resource.scala:164)
	at scalax.io.Resource.acquireFor$(Resource.scala:160)
	at scalax.io.managed.WriterResource.acquireFor(WriterResource.scala:8)
	at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:26)
	at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:26)
	at scalax.io.managed.WriterResource.apply(WriterResource.scala:8)
	at resource.ManagedResourceOperations.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.ManagedResourceOperations.acquireAndGet$(ManagedResourceOperations.scala:25)
	at scalax.io.managed.WriterResource.acquireAndGet(WriterResource.scala:8)
	at resource.ManagedResourceOperations.foreach(ManagedResourceOperations.scala:53)
	at resource.ManagedResourceOperations.foreach$(ManagedResourceOperations.scala:53)
	at scalax.io.managed.WriterResource.foreach(WriterResource.scala:8)
	at scalax.io.WriteChars.writeStrings(WriteChars.scala:78)
	at scalax.io.WriteChars.writeStrings$(WriteChars.scala:77)
	at scalax.io.managed.WriterResource.writeStrings(WriterResource.scala:8)
	at scalax.io.Output.writeStrings(Output.scala:125)
	at scalax.io.Output.writeStrings$(Output.scala:124)
	at scalax.file.FileOps.writeStrings(FileOps.scala:78)
	at com.madgag.git.bfg.cleaner.CLIReporter.reportFiles$1(Reporter.scala:229)
	at com.madgag.git.bfg.cleaner.CLIReporter.reportResults(Reporter.scala:243)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.updateRefsWithCleanedIds$1(RepoRewriter.scala:140)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:147)
	at com.madgag.git.bfg.cli.Main$.$anonfun$new$1(Main.scala:60)
	at com.madgag.git.bfg.cli.Main$.$anonfun$new$1$adapted(Main.scala:35)
	at scala.Option.map(Option.scala:146)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:35)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 5 more
```
