### ISSUE TITLE
org.eclipse.jgit.errors.LargeObjectException exceeds size limit

### ISSUE THREAD

**Issue by sufanglei** [rtyley/bfg-repo-cleaner#473]
Cleaning commits:        12% ( 8289/69073)java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at use.newer.java.Util.invokeMainMethod(Util.java:89)
	at use.newer.java.Util.executeMainProgram(Util.java:28)
	at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
	at use.newer.java.Version8.main(Version8.java:5)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: beae16753e6adc94c9a322e05e4a6480eca81f61 exceeds size limit

**Comment by sufanglei** [comment]
--massive-non-file-objects-sized-up-to ${size}

**Comment by sufanglei** [comment]
--massive-non-file-objects-sized-up-to ${size}
