### ISSUE TITLE
How fix "Cleaning commits:        92% (1199/1303)java.lang.reflect.InvocationTargetException"?

### ISSUE THREAD

**Issue by test346457** [rtyley/bfg-repo-cleaner#497]
Protected commits
-----------------

You're not protecting any commits, which means the BFG will modify the contents of even *current* commits.

This isn't recommended - ideally, if your current commits are dirty, you should fix up your working copy and commit that, check that your build still works, and only then run the B
FG to clean up your history.

Cleaning
--------

Found 1303 commits
Cleaning commits:        92% (1199/1303)java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at use.newer.java.Util.invokeMainMethod(Util.java:89)
        at use.newer.java.Util.executeMainProgram(Util.java:28)
        at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
        at use.newer.java.Version8.main(Version8.java:5)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.Unchecked
ExecutionException: org.eclipse.jgit.errors.LargeObjectException: 9223e589a585c254e196dc75bdfeb05962621996 exceeds size limit
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at com.madgag.git.bfg.MemoUtil$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.$anonfun$rewrite$6(RepoRewriter.scala:113)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.$anonfun$rewrite$6$adapted(RepoRewriter.scala:112)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.$anonfun$rewrite$3(RepoRewriter.scala:112)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at com.madgag.git.bfg.Timing$.measureTask(timing.scala:40)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:104)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:145)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1(Main.scala:60)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1$adapted(Main.scala:35)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:35)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
        ... 8 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectExceptio
n: 9223e589a585c254e196dc75bdfeb05962621996 exceeds size limit
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at com.madgag.git.bfg.MemoUtil$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.$anonfun$uncachedClean$1(ObjectIdCleaner.scala:87)
        at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        ... 35 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 9223e589a585c254e196dc75bdfeb05962621996 exceeds size limit
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at com.madgag.git.bfg.MemoUtil$$anon$1.apply(memo.scala:61)
        at com.madgag.git.bfg.model.CommitArcs.cleanWith(Commit.scala:60)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.$anonfun$cleanCommit$1(ObjectIdCleaner.scala:102)
        at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        ... 45 more
Caused by: org.eclipse.jgit.errors.LargeObjectException: 9223e589a585c254e196dc75bdfeb05962621996 exceeds size limit
        at org.eclipse.jgit.internal.storage.file.LargePackedWholeObject.getCachedBytes(LargePackedWholeObject.java:98)
        at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:214)
        at com.madgag.git.bfg.model.Tree$.entriesFor(Tree.scala:39)
        at com.madgag.git.bfg.cleaner.ObjectIdCleaner.$anonfun$cleanTree$1(ObjectIdCleaner.scala:119)
        at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        ... 56 more

**Comment by test346457** [comment]
Use for fix: bfg-1.14.0.jar --massive-non-file-objects-sized-up-to 20M
