### ISSUE TITLE
getting MissingObjectException when trying to delete files

### ISSUE THREAD

**Issue by davecazz** [rtyley/bfg-repo-cleaner#71]
Hello, 

I'm tying to delete some data files from my project that are >100mb so I can upload it to github.

I did a clean git clone --mirror https://realmacsoftware.git.beanstalkapp.com/hatch.git before running bfg.

This is the output of my attempt.

hatchcleanup Dave$ java -jar bfg.jar --delete-files *.blob hatch.git

Using repo : /Users/Dave/git/HatchCleanup/hatch.git

Found 17214 objects to protect
Found 10 tag-pointing refs : refs/tags/1.0b1, refs/tags/1.0b2, refs/tags/1.0b3, ...
Found 37 commit-pointing refs : HEAD, refs/heads/BetaBuild1.4x1, refs/heads/BetaBuild1.4x2, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 15980636 (protected by 'HEAD')

Cleaning
--------

Found 4414 commits
Cleaning commits:       100% (4414/4414)
Cleaning commits completed in 5,711 ms.

Updating 45 Refs
----------------

	Ref                             Before     After   
	---------------------------------------------------
	refs/heads/BetaBuild1.4x1     | a3165b53 | 7523b72e
	refs/heads/BetaBuild1.4x2     | 6f96cd62 | c00f5c40
	refs/heads/BetaBuild1.4x3     | c57f6507 | b9e3032b
	refs/heads/BetaBuild1.4x4     | ce9e59db | 9b94ab26
	refs/heads/BetaBuild1.4x5     | aa38100c | b43d8c7a
	refs/heads/BetaBuild1.4x6     | e9751f5b | 7652c9a0
	refs/heads/DaveLearning       | 2c935aed | aa74b047
	refs/heads/Release1.4         | 8a329fb4 | 6688cdbb
	refs/heads/Release1.4.1       | fbfc4f1d | 7629b7da
	refs/heads/Release1.4.2       | 8aad1dec | b66ee962
	refs/heads/Release1.4.3hotfix | 4f625f64 | 06ea68b0
	refs/heads/beta1.4.2x1        | ac0218d1 | f1ef5df8
	refs/heads/dev-1.4.1          | 28c8d7f2 | b87e5e40
	refs/heads/dev-1.4.2          | 15980636 | ef71a44f
	refs/heads/dev1.5             | 265307d1 | a026a1d5
	...

Updating references:    100% (45/45)
...Ref update completed in 40 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	.............................DDDDDDDDDDDDDDDDDDDDDDDDDDDmmmm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After   
	-------------------------------------------
	First modified commit | 71515d28 | d617d681
	Last dirty commit     | f80eb8c1 | 1e996b51

Deleted files
-------------

Exception in thread "main" org.eclipse.jgit.errors.MissingObjectException: Missing unknown ef459cb2ebd6569071ba4361f3ed69e780eb3082
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at com.madgag.git.package$RichObjectId.open(package.scala:209)
	at com.madgag.git.package$RichObjectId.sizeOpt(package.scala:212)
	at com.madgag.git.bfg.cleaner.CLIReporter$$anonfun$reportResults$3$$anonfun$apply$11.apply(Reporter.scala:242)
	at com.madgag.git.bfg.cleaner.CLIReporter$$anonfun$reportResults$3$$anonfun$apply$11.apply(Reporter.scala:242)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at com.madgag.git.bfg.cleaner.CLIReporter$$anonfun$reportResults$3.apply(Reporter.scala:242)
	at com.madgag.git.bfg.cleaner.CLIReporter$$anonfun$reportResults$3.apply(Reporter.scala:241)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.RedBlackTree$._foreach(RedBlackTree.scala:101)
	at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:97)
	at scala.collection.immutable.TreeMap.foreach(TreeMap.scala:203)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.TreeMap.map(TreeMap.scala:48)
	at com.madgag.git.bfg.cleaner.CLIReporter.reportFiles$1(Reporter.scala:227)
	at com.madgag.git.bfg.cleaner.CLIReporter.reportResults(Reporter.scala:243)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.updateRefsWithCleanedIds$1(RepoRewriter.scala:139)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:146)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:59)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
	at scala.Option.map(Option.scala:145)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
shitcan:hatchcleanup Dave$

**Comment by rtyley** [comment]
@davecazz thanks for this bug report, really appreciate it! There's some good news, in that the crash happened _after_ the BFG had finished cleaning your repo - it actually crashed while just reporting on the work it did (specifically, which files it deleted) - so you should be fine to use the resulting cleaned repository.

This issue looks like a bug that was introduced with when the 'report deleted files' feature was add in [v1.12.0](https://github.com/rtyley/bfg-repo-cleaner/releases/tag/v1.12.0). It's a puzzler why it should crash like this, and being able to recreate the issue would really help - are you able to share a copy of the repository with me?

Failing that, a zipped copy of  'hatch.git.bfg-report' would be good.

**Comment by davecazz** [comment]
Hi Roberto,

The repo is really big and I don’t think my client would want me to give access to it.

I don’t see a hatch.git.bfg-report anywhere

**Comment by dwabyick** [comment]
I had the same issue, and sadly, cannot share my repos either. :/

**Comment by rtyley** [comment]
> I had the same issue

@dwabyick could you post the full output from the console in a gist, and send me a zipped copy of the `.bfg-report` folder?

**Comment by dwabyick** [comment]
@rtyley - can you email me at dwabyick@yahoo.com and I'll send ... It did not create a `.bfg-report` folder. thank you!

**Comment by rtyley** [comment]
A hopefully-fixing change for this issue should be in BFG v1.12.3 -  I haven't been able to reproduce the issue locally, could you download and see if it resolved the issue for you?
