### ISSUE TITLE
Out of memory loading unknown object

### ISSUE THREAD

**Issue by jbrooksuk** [rtyley/bfg-repo-cleaner#75]
I've been trying to run:

```bash
$ bfg --strip-blobs-bigger-than 100M ~/Desktop/repo.git
```

Where `repo.git` is just a `mirror` repository, which isn't particularly big, but does contain these 100M files.

But every time, I get this error:

```
Exception in thread "main" org.eclipse.jgit.errors.LargeObjectException$OutOfMemory: Out of memory loading unknown object
	at org.eclipse.jgit.internal.storage.file.PackFile.load(PackFile.java:827)
	at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:257)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:411)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:380)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:372)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at com.madgag.git.bfg.GitUtil$$anonfun$biggestBlobs$1$$anonfun$apply$2.apply(GitUtil.scala:78)
	at com.madgag.git.bfg.GitUtil$$anonfun$biggestBlobs$1$$anonfun$apply$2.apply(GitUtil.scala:78)
	at scala.collection.immutable.Stream.filter(Stream.scala:519)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1288)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1288)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:936)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:936)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at com.madgag.git.bfg.cli.CLIConfig.blobRemover$lzycompute$1(CLIConfig.scala:204)
	at com.madgag.git.bfg.cli.CLIConfig.blobRemover$1(CLIConfig.scala:195)
	at com.madgag.git.bfg.cli.CLIConfig.treeBlobCleaners$lzycompute(CLIConfig.scala:216)
	at com.madgag.git.bfg.cli.CLIConfig.treeBlobCleaners(CLIConfig.scala:191)
	at com.madgag.git.bfg.cli.CLIConfig.definesNoWork$lzycompute(CLIConfig.scala:219)
	at com.madgag.git.bfg.cli.CLIConfig.definesNoWork(CLIConfig.scala:219)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:53)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
	at scala.Option.map(Option.scala:145)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.file.PackFile.load(PackFile.java:824)
	at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:257)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:411)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:380)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:372)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at com.madgag.git.bfg.GitUtil$$anonfun$biggestBlobs$1$$anonfun$apply$2.apply(GitUtil.scala:78)
	at com.madgag.git.bfg.GitUtil$$anonfun$biggestBlobs$1$$anonfun$apply$2.apply(GitUtil.scala:78)
	at scala.collection.immutable.Stream.filter(Stream.scala:519)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1288)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1288)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:936)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:936)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at com.madgag.git.bfg.cli.CLIConfig.blobRemover$lzycompute$1(CLIConfig.scala:204)
	at com.madgag.git.bfg.cli.CLIConfig.blobRemover$1(CLIConfig.scala:195)
	at com.madgag.git.bfg.cli.CLIConfig.treeBlobCleaners$lzycompute(CLIConfig.scala:216)
	at com.madgag.git.bfg.cli.CLIConfig.treeBlobCleaners(CLIConfig.scala:191)
	at com.madgag.git.bfg.cli.CLIConfig.definesNoWork$lzycompute(CLIConfig.scala:219)
```

I've actually ran bfg on another repository which was much bigger too. Also, I've just updated Java with no luck.

**Comment by rtyley** [comment]
Thanks for reporting this @jbrooksuk - it's a surprising error, maybe a regression.

> repo.git is just a mirror repository, which isn't particularly big, but does contain these 100M files.

Are you able to share this repository with me?



> I've actually ran bfg on another repository which was much bigger too.

I'm guessing the BFG worked for you on that repo?



> Also, I've just updated Java with no luck.

Can you give:

* Operating System
* Java version
* BFG version

**Comment by jbrooksuk** [comment]
Hi @rtyley thanks for your reply!

1. I'm not able to share the repository with you I'm afraid, it's a consumer website that contains a lot of private information.
2. Yeah BFG worked on the other repo for me just fine.
3. Sure:
    - **Operating System:** OSX 10.10.1
    - **Java version:** 1.6.0_65
    - **BFG version:** 1.12.0

**Comment by rtyley** [comment]
> I'm not able to share the repository with you I'm afraid

That makes reproducing this issue much harder :-( I'll see what I can do.

**Comment by jbrooksuk** [comment]
Sorry about that :( If I could give you access, then I'd be more than happy to.

By the way, I get the same error regardless of whether I try to strip blobs of 100M or 1M.

**Comment by rtyley** [comment]
It's not too unexpected, I only ask on the off-chance.

What's the total size of the pack file?

**Comment by jbrooksuk** [comment]
```
392K	objects/pack/pack-1c7dc5a50e3650d4bcb3d490b2dca81e8fceccaa.idx
843M	objects/pack/pack-1c7dc5a50e3650d4bcb3d490b2dca81e8fceccaa.pack
```

**Comment by rtyley** [comment]
Can you send me the output of this:

```
git verify-pack -v objects/pack/pack-*.idx
```

...it's not sensitive information, just gives me information about the size-distribution of objects in your packfile.

**Comment by jbrooksuk** [comment]
https://gist.github.com/jbrooksuk/de76b30d4c786d7f672d

**Comment by rtyley** [comment]
I've made a change which should fix this issue, it's been released as BFG v1.12.1 - it should cycle though Maven central and be ready for download within a hour or so. Let me know how it goes, and if it fixes the problem!

Also, if it does work out for you, consider making a donation to the project at https://www.bountysource.com/teams/bfg-repo-cleaner

**Comment by donnib** [comment]
I did a git verify-pack -v objects/pack/pack-*.idx and got a text file of 336MB, do you want this ?

**Comment by rtyley** [comment]
Yeah, it should compress reasonably well.

**Comment by donnib** [comment]
https://drive.google.com/file/d/0B-Awyixw7TFnbU80MlRuTGxUa1E/view?usp=sharing

**Comment by buley** [comment]
I was running into this issue. Saw the comments here, updated to https://github.com/rtyley/bfg-repo-cleaner/releases/tag/git-lfs-alpha and now I'm chugging along. Thanks @rtyley!

**Comment by larsxschneider** [comment]
@donnib @buley Did you try to increase the Java heap size?
